config/routes.rb
Rails.application.routes.draw do
  resources :pictures

  root 'home#index'

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :collections, only: [:new, :edit, :create, :update, :destroy] do
    resources :monuments
  end
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :monuments
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :monuments
end

app/models/monument.rb
class Monument < ActiveRecord::Base
  belongs_to :collection
  belongs_to :category
  has_many :pictures
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :monument
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :collections
  has_many :categories

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:id]) if session[:id]
  end
  helper_method :current_user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def new
    @category = current_user.categories.build
  end

  def edit
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to :root, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to :root, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to :root, notice: 'Category was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:edit, :update, :destroy]

  def new
    @collection = current_user.collections.build
  end

  def edit
  end

  def create
    @collection = current_user.collections.build(collection_params)
    if @collection.save
      redirect_to :root, notice: 'Collection was successfully created.'
    else
      render :new
    end
  end

  def update
    if @collection.update(collection_params)
      redirect_to :root, notice: 'Collection was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @collection.destroy
    redirect_to :root, notice: 'Collection was successfully destroyed.'
  end

  private

  def set_collection
    @collection = current_user.collections.find(params[:id])
  end

  def collection_params
    params.require(:collection).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @collections = current_user.collections
      @categories = current_user.categories
    else
      @users = User.all
    end
  end
end

app/controllers/monuments_controller.rb
class MonumentsController < ApplicationController
  before_action :find_collection
  before_action :find_monument, only: [:edit, :update, :destroy]

  def new
    @monument = @collection.monuments.build
  end

  def edit
  end

  def create
    @monument = @collection.monuments.build(monument_params)

    if @monument.save
      redirect_to :root, notice: 'Monument was successfully created.'
    else
      render :new
    end
  end

  def update
    if @monument.update(monument_params)
      redirect_to :root, notice: 'Monument was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @monument.destroy
    redirect_to :root, notice: 'Monument was successfully destroyed.'
  end

  private
    def find_collection
      @collection = Collection.find(params[:collection_id])
    end

    def find_monument
      @monument = @collection.monuments.find(params[:id])
    end

    def monument_params
      params.require(:monument).permit(:name, :description, :category_id)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:data, :name, :description, :date, :monument_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(login: session_params[:login])
    if user && user.authenticate(session_params[:password])
      session[:id] = user.id
      redirect_to :root, notice: "Successful Sign In!"
    else
      redirect_to new_session_path, notice: 'Failed Sign In!'
    end
  end

  def destroy
    session[:id] = nil
    redirect_to :root
  end

  private

  def session_params
    params.permit(:login, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:id] = @user.id
      redirect_to :root, notice: "Successful Sign Up!"
    else
      redirect_to :back, alert: "Failed Sign Up!"
    end
  end

  private

  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/categories/_category.html.erb
<p>
  <h3>
    <%= category.name %>
    <%= link_to 'Edit', edit_category_path(category) %> |
    <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
  </h3>
</p>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.user %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @category.user %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/collections/_collection.html.erb
<p>
  <h3>
    <%= collection.name %>
    <%= link_to 'Edit', edit_collection_path(collection) %> |
    <%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %>
  </h3>
  <%= render collection.monuments %>
  <%= link_to 'New Monument', new_collection_monument_path(collection, collection.monuments.build) %>
</p>

app/views/collections/_collection_ruler.html.erb
<hr>

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render 'form' %>

app/views/home/index.html.erb
<% if current_user %>
  <h1>Collections <%= link_to 'New Collection', new_collection_path %></h1>
  <%= render partial: @collections, spacer_template: "shared/ruler" %>
  <h1>Categories <%= link_to 'New Category', new_category_path %></h1>
  <%= render partial: @categories, spacer_template: "shared/ruler" %>
<% else %>
  <h1>Users</h1>
  <%= render @users %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monuments</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if session[:id] %>
  Signed as: <%= User.find(session[:id]).login %>
  <%= link_to 'Sign Out', session_path(session[:id]), method: :delete %>
<% else %>
  <%= link_to 'Sign Up', new_user_path %>
  <%= link_to 'Sign In', new_session_path %>
<% end %>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

<%= yield %>

</body>
</html>

app/views/monuments/_form.html.erb
<%= form_for([@collection, @monument]) do |f| %>
  <% if @monument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monument.errors.count, "error") %> prohibited this monument from being saved:</h2>

      <ul>
      <% @monument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
    <div class="field">
      <%= f.label :category %><br>
      <%= f.collection_select :category_id, current_user.categories, :id, :name, :selected => @monument.category_id %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monuments/_monument.html.erb
<p>
  <%= monument.name %> (<%= monument.category.name %>)
  <%= link_to 'Edit', edit_collection_monument_path(monument.collection, monument) %> |
  <%= link_to 'Destroy', collection_monument_path(monument.collection, monument), method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/monuments/edit.html.erb
<h1>Editing monument</h1>

<%= render 'form' %>

app/views/monuments/new.html.erb
<h1>New monument</h1>

<%= render 'form' %>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_field :data %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :monument_id %><br>
    <%= f.text_field :monument_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Name</th>
      <th>Description</th>
      <th>Date</th>
      <th>Monument</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.data %></td>
        <td><%= picture.name %></td>
        <td><%= picture.description %></td>
        <td><%= picture.date %></td>
        <td><%= picture.monument %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @picture.data %>
</p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @picture.date %>
</p>

<p>
  <strong>Monument:</strong>
  <%= @picture.monument %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/shared/_ruler.html.erb
<hr>

app/views/users/_user.html.erb
<p><%= user.login %></p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <%= f.label :login %>
  <%= f.text_field :login %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>